version: '3'
services:
    exchange-service:
#        container-name: 'exchange-info-service'
        image: multy-back-exchange-info:last
        #restart: always
        ports:
          - "${EXCHANGE_INFO_SERVICE_PORT}:80"
        depends_on:
          - postgres
        links:
          - postgres:multy-back-exchange-info-db
        environment:
            PGHOST: postgres
            PGPORT: 5432
            PGDATABASE: ${EXCHANGE_INFO_SERVICE_POSTGRES_DB}
            PGUSER: "${EXCHANGE_INFO_SERVICE_POSTGRES_USER}"
        volumes:
            - ../Multy-back-exchange-service:/go/src/github.com/Enmk/Multy-back-exchange-service

# docker run -d --name pg10 -v /Users/enmk/proj/PG_DATA_DIR/data:/var/lib/postgresql/data -e POSTGRES_PASSWORD=password postgres:10
    postgres:
#        container-name: 'exchange-info-service-db'
        image: postgres:10
        restart: always
        environment:
            POSTGRES_DB: ${EXCHANGE_INFO_SERVICE_POSTGRES_DB}
            POSTGRES_USER: ${EXCHANGE_INFO_SERVICE_POSTGRES_USER}
            POSTGRES_PASSWORD: ${EXCHANGE_INFO_SERVICE_POSTGRES_PASSWORD}
        volumes:
            # persitent storage of the DB
            - ./postgres-data:/var/lib/postgresql/data
            # DB schema, executed every time container starts up
            - ./sql/setupDB.sql:/docker-entrypoint-initdb.d/init.sql